project:
  type: website
  output-dir: docs

website:
  title: "Bayard-V-T-portfolio"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About Me"
      - href: Portfolio/Portfolio.html
        text: "Project"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual