s---
title: "Project: Example for Class"
format: html
execute: 
  echo: false
  warning: false
  message: false
embed-resources: true
---

```{r}
#| label: setup

library(readxl) 
library(tidyverse)
library(esquisse)
```

```{r}
expensives <- read.csv("Military Expenditure.csv")
Military_data <- expensives %>%
  pivot_longer(
    cols = starts_with("X"),
    names_to = "year",
    names_prefix = "X",     # remove the "X" prefix
    values_to = "Military_expensives"
  )
gdp_per_capita <- read.csv("GDP_per_capita.csv")
Military_data_GDP_per_capita <- gdp_per_capita %>%
  pivot_longer(
    cols = starts_with("X"),
    names_to = "year",
    names_prefix = "X",     # remove the "X" prefix
    values_to = "GDP"
  )
options(scipen = 0)
gdp <- read.csv("GDP.csv")
Military_data_GDP <- gdp %>%
  pivot_longer(
    cols = starts_with("X"),
    names_to = "year",
    names_prefix = "X",     # remove the "X" prefix
    values_to = "GDP"
  )
Military_data_GDP_per_capita <- Military_data_GDP_per_capita %>%
  rename(Name = Country.Name, Code = Country.Code, GDP_per_capita_Indicator.Name = Indicator.Name, GDP_per_capita = GDP)

Military_data_GDP <- Military_data_GDP %>%
  rename(Name = Country.Name, Code = Country.Code, GDP_Indicator.Name = Indicator.Name)

Military_data <- Military_data %>%
  rename(Mil_budget_Inidcator.Name = Indicator.Name)
```

```{r}
combined_data <- left_join(Military_data, Military_data_GDP, by = c("Name", "year")) %>%
  select(-Code.y,-Indicator.Code) %>%
  relocate("year", .after = "Type") %>%
  rename(Country.Code = Code.x) %>%
  drop_na()
combined_data_per_capita <- left_join(combined_data, Military_data_GDP_per_capita, by = c("Name",
                                                                                          "year")) %>%
  select(-Indicator.Code, -Code)
combined_data_country <- combined_data_per_capita %>%
  filter(Type == "Country")
combined_data_no_country <- combined_data_per_capita %>%
  filter(Type != "Country")
combined_data_region_economically<- combined_data_per_capita %>%
  filter(Type == "Regions Clubbed Economically")
combined_data_region_economically_income <- combined_data_region_economically %>%
  filter(Name %in% c("High income",
                     "Upper middle income",
                     "Lower middle income",
                     "Low & middle income",
                     "Low income")) %>%
  filter(year %in% c(1989,
                     2018)) %>%
  mutate(Name = factor(Name, levels = c("High income", 
                                        "Upper middle income", 
                                        "Lower middle income", 
                                        "Low & middle income", 
                                        "Low income")))
combined_data_region_geographically <- combined_data_per_capita %>%
  filter(Type == "Regions Clubbed Geographically") %>%
  filter(Name != "World")
```

```{r}
unique(combined_data_region_economically_income$Name)
```

```{r}
#esquisse::esquisser(combined_data_region_economically_income)
```

```{r}
ggplot(combined_data_region_geographically) +
  aes(
    x = year,
    y = GDP,
    colour = Name,
    size = Military_expensives
  ) +
  geom_point() +
  scale_color_viridis_d(option = "plasma", direction = -1) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45L,
    vjust = 0.5)
  )
```

```{r}
ggplot(combined_data_region_economically_income) +
  aes(
    x = Name,
    y = Military_expensives,
    fill = GDP_per_capita
  ) +
  geom_col() +
  scale_fill_viridis_c(option = "viridis", direction = 1) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45L,
    vjust = 0.5)
  ) +
  facet_wrap(vars(year))

```
